#!/usr/bin/env bash

NAME_FILE_ARCH='archive.tar.gz'
PATH_FILE_ARCH="docs/${NAME_FILE_ARCH}"

# Remove old archive
rm -rf $NAME_ARCH

# Testing
echo -n '- Suppose testing here ... '
if [ $? -ne 0 ]; then
    echo 'NG'
    echo 'You need to pass the test first.'
fi
echo 'OK'

# Moving to bin
cp src/testcmd.sh bin/testcmd

# Archive
tar -zcvf $PATH_FILE_ARCH bin

# CheckSUM
shasum -a 256 $PATH_FILE_ARCH | awk '{ print $1 }'
